### ISSUE TITLE
Upgrading metrics-core

### ISSUE THREAD

**Issue by gregsymons** [erikvanoosten/sentries#1]
Are there any technical reasons you're still on metrics-core 2.2.0? I'm thinking of recommending this library to our developers, but we're using metrics 3.0.1. I'd be willing to do the work for the upgrade if you can tell me where I need to look to do it.

**Comment by erikvanoosten** [comment]
Hi Greg,

At my company we're still at metrics 2.1.5. But there is no reason to stay there except for finding time to upgrade.

Please go ahead and do a pull request. You can drop scala 2.9 support if you want.

Upgrading is easy. Just replace the import statements and fix till it works ☺

Please do not use 3.0.1 but the actual latest version. 3.0.1 has some annoying bugs.

In 2 weeks I'll be able tot help you beter.

Kind regards,
    Erik.

**Comment by erikvanoosten** [comment]
Closing as Sentries is in no-maintenance-intended mode.
